import type { AppSettings, DashboardData, Draft, LogEntry, Product, TaskItem } from "./types";

export const demoProducts: Product[] = [
  {
    id: 1001,
    source: "1688",
    source_product_id: "731928451042",
    source_url: "https://detail.1688.com/offer/731928451042.html",
    title_original: "2026春季新款女式轻量防泼水休闲风衣外套",
    description_original: "轻量防泼水面料，宽松版型，适合春秋日常通勤。支持一件代发。",
    category_original: "女装 / 风衣",
    supplier: "杭州米岚服饰有限公司",
    purchase_price: 68,
    currency: "CNY",
    images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=240&q=80"],
    sku_count: 12,
    variants: [
      { id: 1, internal_sku: "OA-1001-BE-S", color: "米白", size: "S", purchase_price: 68, stock: 82 },
      { id: 2, internal_sku: "OA-1001-BE-M", color: "米白", size: "M", purchase_price: 68, stock: 116 },
      { id: 3, internal_sku: "OA-1001-GR-M", color: "灰绿", size: "M", purchase_price: 71, stock: 63 },
    ],
    attributes: { 材质: "聚酯纤维", 风格: "通勤", 季节: "春秋" },
    stock: 438,
    ai_status: "completed",
    ozon_status: "review",
    estimated_price: 2990,
    estimated_margin: 36.8,
    ai_result: {
      title_ru: "Женская лёгкая водоотталкивающая куртка свободного кроя",
      description_ru: "Лёгкая женская куртка для города и путешествий. Водоотталкивающая ткань, свободный крой и удобная посадка.",
      category_suggestion: "Одежда / Женская одежда / Куртки",
      attributes: { Материал: "Полиэстер", Сезон: "Демисезон", Стиль: "Повседневный" },
      risks: ["请人工确认防泼水等级，避免使用“完全防水”描述"],
      provider: "MockAI",
      model: "mock-product-v1",
      tokens: 0,
      duration_ms: 842,
      created_at: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    },
    created_at: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
  },
  {
    id: 1002,
    source: "1688",
    title_original: "厨房硅胶锅铲耐高温不粘锅专用厨具套装",
    supplier: "阳江优厨日用品厂",
    purchase_price: 24.8,
    currency: "CNY",
    images: ["https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=240&q=80"],
    sku_count: 5,
    stock: 1200,
    ai_status: "pending",
    ozon_status: "not_created",
    estimated_price: 1190,
    estimated_margin: 42.1,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 1003,
    source: "1688",
    title_original: "宠物猫咪自嗨球智能滚动逗猫玩具充电款",
    supplier: "义乌灵宠科技",
    purchase_price: 19.5,
    currency: "CNY",
    images: ["https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&w=240&q=80"],
    sku_count: 3,
    stock: 670,
    ai_status: "processing",
    ozon_status: "not_created",
    estimated_price: 990,
    estimated_margin: 39.4,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 1004,
    source: "1688",
    title_original: "桌面折叠收纳盒家用多功能带盖整理箱",
    supplier: "台州简家塑业",
    purchase_price: 13.2,
    currency: "CNY",
    images: ["https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=240&q=80"],
    sku_count: 8,
    stock: 0,
    ai_status: "failed",
    ozon_status: "not_created",
    estimated_price: 790,
    estimated_margin: 30.2,
    created_at: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
  },
];

export const demoLogs: LogEntry[] = [
  { id: 1, level: "ERROR", module: "AI", message: "商品 #1004 加工失败：模拟模型返回超时，任务将在手动重试后继续", created_at: new Date(Date.now() - 13 * 60 * 1000).toISOString() },
  { id: 2, level: "WARNING", module: "Ozon", message: "类目属性“ТН ВЭД”需要人工确认", created_at: new Date(Date.now() - 28 * 60 * 1000).toISOString() },
  { id: 3, level: "INFO", module: "1688", message: "商品 731928451042 已采集并保存 12 个 SKU", created_at: new Date(Date.now() - 44 * 60 * 1000).toISOString() },
  { id: 4, level: "INFO", module: "任务", message: "AI 商品加工任务 #T-2401 执行完成", created_at: new Date(Date.now() - 51 * 60 * 1000).toISOString() },
  { id: 5, level: "INFO", module: "数据库", message: "本地数据存储连接正常", created_at: new Date(Date.now() - 67 * 60 * 1000).toISOString() },
];

export const demoTasks: TaskItem[] = [
  { id: "T-2403", type: "AI 商品加工", status: "running", progress: 68, started_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(), retries: 0, message: "正在生成俄语标题与属性" },
  { id: "T-2402", type: "1688 商品采集", status: "success", progress: 100, started_at: new Date(Date.now() - 19 * 60 * 1000).toISOString(), ended_at: new Date(Date.now() - 18 * 60 * 1000).toISOString(), retries: 0 },
  { id: "T-2401", type: "生成 Ozon 草稿", status: "success", progress: 100, started_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(), ended_at: new Date(Date.now() - 51 * 60 * 1000).toISOString(), retries: 0 },
  { id: "T-2399", type: "AI 商品加工", status: "failed", progress: 47, started_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), ended_at: new Date(Date.now() - 2 * 60 * 60 * 1000 + 36000).toISOString(), retries: 2, error: "模型服务响应超时" },
  { id: "T-2398", type: "图片处理", status: "pending", progress: 0, created_at: new Date(Date.now() - 6 * 60 * 1000).toISOString(), retries: 0 },
];

export const demoDrafts: Draft[] = [
  {
    id: 501,
    product_id: 1001,
    title_ru: "Женская лёгкая водоотталкивающая куртка свободного кроя",
    description_ru: "Лёгкая женская куртка для города и путешествий. Водоотталкивающая ткань, свободный крой, практичные карманы и удобная посадка.",
    category_id: 17028922,
    category_name: "Одежда / Женская одежда / Куртки",
    attributes: { Бренд: "Нет бренда", Материал: "Полиэстер", Сезон: "Демисезон", Цвет: "Бежевый" },
    images: demoProducts[0].images,
    skus: [
      { id: 1, sku: "OA-1001-BE-S", name: "米白 / S", price: 2990, stock: 82, color: "米白", size: "S" },
      { id: 2, sku: "OA-1001-BE-M", name: "米白 / M", price: 2990, stock: 116, color: "米白", size: "M" },
      { id: 3, sku: "OA-1001-GR-M", name: "灰绿 / M", price: 3090, stock: 63, color: "灰绿", size: "M" },
    ],
    status: "review",
    suggested_price: 2990,
    profit_margin: 36.8,
    updated_at: new Date(Date.now() - 16 * 60 * 1000).toISOString(),
  },
  {
    id: 502,
    product_id: 1005,
    title_ru: "Набор герметичных контейнеров для хранения продуктов",
    category_name: "Дом и сад / Хранение продуктов",
    status: "draft",
    suggested_price: 1590,
    profit_margin: 33.5,
    updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
];

export const demoDashboard: DashboardData = {
  product_total: 128,
  pending_ai: 17,
  pending_review: 8,
  published: 63,
  task_counts: { running: 1, pending: 1, success: 3, failed: 1 },
  recent_products: demoProducts.slice(0, 3),
  recent_errors: demoLogs.filter((log) => log.level === "ERROR"),
};

export const demoSettings: AppSettings = {
  ai_provider: "mock",
  ai_base_url: null,
  ai_model: "mock-product-processor-v1",
  ai_api_key_configured: false,
  ai_temperature: 0.2,
  ozon_client_id_configured: false,
  ozon_api_key_configured: false,
  ozon_mode: "mock",
  source_provider: "mock",
  database_backend: "sqlite",
  exchange_rate: 12.6,
  domestic_shipping: 5,
  international_shipping: 28,
  ozon_commission_rate: 18,
  target_margin: 30,
};
